### PR TITLE
add transactions table in schema md

### PR DESCRIPTION
**Pull request by mac-obl**
This should update the json and markdown to add a general schema for transactions, based on this slack thread; 
https://openblockteam.slack.com/archives/C07ATU17H55/p1729874924858139?thread_ts=1729802319.038969&cid=C07ATU17H55

### CODE REVIEW

**Comment by bntyee** [comment]
@mac-obl Nice. I think it makes sense to add this under the existing general schema vs game specific. @melotik for additional thoughts tho

**Comment by mac-obl** [comment]
I believe it is in the general folder? I didn't see a game folder?

**Comment by bntyee** [comment]
> I believe it is in the general folder? I didn't see a game folder?

O, I mean you can make one.

**Review by bntyee — APPROVED** [review]

**Comment by melotik** [comment]
Missed the JSON part, we should be editing the JSON, then generating the markdown file

**Pull request merged**
